# Generated by Django 3.2.6 on 2021-08-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('id_number', models.CharField(max_length=12)),
                ('farm_number', models.CharField(max_length=12)),
                ('farm_title_deed', models.FileField(upload_to='')),
                ('products', models.CharField(choices=[('G', 'Groceries'), ('F', 'Fruits'), ('D', 'Dairies'), ('M', 'Meat')], max_length=1)),
                ('region', models.CharField(choices=[('N', 'Nairobi'), ('K', 'Kiambu'), ('KD', 'Narok'), ('N', 'Nyeri'), ('T', 'Thika'), ('E', 'Embu'), ('MR', 'Meru')], max_length=3)),
            ],
        ),
    ]
