# Generated by Django 3.2.6 on 2021-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=18)),
                ('product_id', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_supplier', models.CharField(max_length=18)),
                ('product_price', models.CharField(max_length=10)),
                ('product_category', models.CharField(choices=[('F', 'Fruits'), ('G', 'Groceries'), ('M', 'Meat'), ('S', 'Spices')], max_length=1)),
            ],
        ),
    ]
