# Generated by Django 3.2.6 on 2021-08-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=20)),
                ('order_client', models.CharField(max_length=20)),
                ('order_location', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('order_cost', models.CharField(max_length=15)),
            ],
        ),
    ]
